const productData = [
    { ID: 1, Emoji: "💻", Name: "Laptop", Category: "Electronics", Link: "#", Price: 1200 },
    { ID: 2, Emoji: "📱", Name: "Smartphone", Category: "Electronics", Link: "#", Price: 800 },
    { ID: 3, Emoji: "🎧", Name: "Bluetooth Headphones", Category: "Electronics", Link: "#", Price: 150 },
    { ID: 4, Emoji: "👟", Name: "Sneakers", Category: "Fashion", Link: "#", Price: 100 },
    { ID: 5, Emoji: "👖", Name: "Jeans", Category: "Fashion", Link: "#", Price: 25 },
    { ID: 6, Emoji: "👕", Name: "T-Shirt", Category: "Fashion", Link: "#", Price: 25 },
    { ID: 7, Emoji: "🔥", Name: "Microwave Oven", Category: "Home Appliances", Link: "#", Price: 200 },
    { ID: 8, Emoji: "🧹", Name: "Vacuum Cleaner", Category: "Home Appliances", Link: "#", Price: 250 },
    { ID: 9, Emoji: "❄️", Name: "Air Conditioner", Category: "Home Appliances", Link: "#", Price: 1000 },
    { ID: 10, Emoji: "📺", Name: "Television", Category: "Electronics", Link: "#", Price: 500 },
    { ID: 11, Emoji: "🎮", Name: "Gaming Console", Category: "Electronics", Link: "#", Price: 300 },
    { ID: 12, Emoji: "🖥️", Name: "Desktop Computer", Category: "Electronics", Link: "#", Price: 900 },
    { ID: 13, Emoji: "💡", Name: "Smart Light Bulb", Category: "Home Appliances", Link: "#", Price: 25 },
    { ID: 14, Emoji: "📸", Name: "Camera", Category: "Electronics", Link: "#", Price: 450 },
    { ID: 15, Emoji: "📚", Name: "Bookshelf", Category: "Furniture", Link: "#", Price: 80 },
    { ID: 16, Emoji: "🛋️", Name: "Sofa", Category: "Furniture", Link: "#", Price: 500 },
    { ID: 17, Emoji: "🪑", Name: "Chair", Category: "Furniture", Link: "#", Price: 75 },
    { ID: 18, Emoji: "🚲", Name: "Bicycle", Category: "Sports", Link: "#", Price: 200 },
    { ID: 19, Emoji: "🏀", Name: "Basketball", Category: "Sports", Link: "#", Price: 20 },
    { ID: 20, Emoji: "⚽", Name: "Soccer Ball", Category: "Sports", Link: "#", Price: 15 },
    { ID: 21, Emoji: "🧑‍🍳", Name: "Chef Knife", Category: "Kitchen", Link: "#", Price: 50 },
    { ID: 22, Emoji: "🍴", Name: "Cutlery Set", Category: "Kitchen", Link: "#", Price: 30 },
    { ID: 23, Emoji: "🥄", Name: "Spoon Set", Category: "Kitchen", Link: "#", Price: 10 },
    { ID: 24, Emoji: "🍽️", Name: "Dinner Plates", Category: "Kitchen", Link: "#", Price: 20 },
    { ID: 25, Emoji: "⛺", Name: "Camping Tent", Category: "Outdoor", Link: "#", Price: 150 },
    { ID: 26, Emoji: "🛶", Name: "Kayak", Category: "Outdoor", Link: "#", Price: 300 },
    { ID: 27, Emoji: "🥾", Name: "Hiking Boots", Category: "Outdoor", Link: "#", Price: 120 },
    { ID: 28, Emoji: "🎒", Name: "Backpack", Category: "Outdoor", Link: "#", Price: 40 },
    { ID: 29, Emoji: "🖨️", Name: "Printer", Category: "Electronics", Link: "#", Price: 150 },
    { ID: 30, Emoji: "💾", Name: "External Hard Drive", Category: "Electronics", Link: "#", Price: 100 },
    { ID: 31, Emoji: "🖋️", Name: "Fountain Pen", Category: "Office Supplies", Link: "#", Price: 20 },
    { ID: 32, Emoji: "📎", Name: "Paper Clips", Category: "Office Supplies", Link: "#", Price: 5 },
    { ID: 33, Emoji: "📏", Name: "Ruler", Category: "Office Supplies", Link: "#", Price: 3 },
    { ID: 34, Emoji: "🗂️", Name: "File Organizer", Category: "Office Supplies", Link: "#", Price: 15 },
    { ID: 35, Emoji: "🎁", Name: "Gift Box", Category: "Miscellaneous", Link: "#", Price: 10 },
    { ID: 36, Emoji: "🎀", Name: "Ribbon", Category: "Miscellaneous", Link: "#", Price: 5 },
    { ID: 37, Emoji: "🌺", Name: "Flower Pot", Category: "Decor", Link: "#", Price: 25 },
    { ID: 38, Emoji: "🖼️", Name: "Wall Art", Category: "Decor", Link: "#", Price: 80 },
    { ID: 39, Emoji: "🕯️", Name: "Candle Set", Category: "Decor", Link: "#", Price: 15 },
    { ID: 40, Emoji: "🪞", Name: "Mirror", Category: "Decor", Link: "#", Price: 50 },
    { ID: 41, Emoji: "👗", Name: "Dress", Category: "Fashion", Link: "#", Price: 50 },
    { ID: 42, Emoji: "👚", Name: "Blouse", Category: "Fashion", Link: "#", Price: 35 },
    { ID: 43, Emoji: "👒", Name: "Hat", Category: "Fashion", Link: "#", Price: 20 },
    { ID: 44, Emoji: "👛", Name: "Purse", Category: "Fashion", Link: "#", Price: 80 },
    { ID: 45, Emoji: "🕶️", Name: "Sunglasses", Category: "Fashion", Link: "#", Price: 40 },
    { ID: 46, Emoji: "👠", Name: "Heels", Category: "Fashion", Link: "#", Price: 60 },
    { ID: 47, Emoji: "🧳", Name: "Luggage", Category: "Fashion", Link: "#", Price: 150 },
    { ID: 48, Emoji: "🧴", Name: "Perfume", Category: "Beauty", Link: "#", Price: 100 },
    { ID: 49, Emoji: "🛀", Name: "Shower Gel", Category: "Beauty", Link: "#", Price: 15 },
    { ID: 50, Emoji: "🧼", Name: "Soap Bar", Category: "Beauty", Link: "#", Price: 5 }
];
